<?php echo $this->doctype();?>
<html>
<head>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
                                ->appendHttpEquiv('Content-Language', 'en-US') ?>

    <?php echo $this->headTitle("Husky CMS")
                    ->setSeparator(' - ')
                    ->setAutoEscape(false) ?>

    <?php echo $this->headScript()?>

    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>

<body class="hc-backend claro">
    <header>
        <div class="container">
            <a href="<?=$this->url('hc-backend/user/logout')?>" class="logout"><?=$this->translate('Exit')?></a>

        </div>
    </header>
    <section class="container">
        <?=$this->content?>
        <div data-dojo-type="hc-backend/layout/Container"
             data-dojo-props="<?=($this->zfcUserIdentity() === false ? '' : 'isAuth: true')?>">
        </div>
    </section>
    <footer>
        <div class="milcrew">
            <a href="http://www.milsdev.com"
               title="<?=$this->translate("Mils copyright title")?>">
                <?=$this->translate("Mils copyright text")?>
            </a>
        </div>
    </footer>

    <script type="text/javascript">
        <?=$this->hc_backend_dojojsconfig()?>
    </script>

    <script type="text/javascript">
        <?=$this->hc_backend_huskyjsconfig()?>
    </script>

    <script type="text/javascript" src="/vendor/dojo/dojo.js"></script>
    <script type="text/javascript">
        require(["dojo/ready",
                 "dojo/dom-style",
                 "dojo/parser",
                 "hc-backend/bootstrap"], function(ready, domStyle) {
                 ready(function(){
                     domStyle.set(dojo.body(), 'visibility', 'visible');
                 });
        });
    </script>
</body>
</html>
