<?php echo $this->doctype();?>
<html>
<head>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
                                ->appendHttpEquiv('Content-Language', 'en-US') ?>

    <?php echo $this->headTitle("Husky CMS")
                    ->setSeparator(' - ')
                    ->setAutoEscape(false) ?>

    <?php echo $this->headScript()?>

    <link href="/js/src/hc-backend/css/images/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>

<body class="hc-backend claro">
    <header>
        <div class="container">
            <span class="site-name">Euromillions</span>
            <a href="<?=$this->url('hc-backend/user/logout')?>" class="logout"></a>

        </div>
    </header>
    <section class="container">
        <?=$this->content?>
        <div data-dojo-type="hc-backend/layout/Container"
             data-dojo-props="<?=($this->zfcUserIdentity() === false ? '' : 'isAuth: true')?>">
        </div>
    </section>
    <footer>
        <div class="mils container">
            <a href="http://milsdev.com"
               title="<?=$this->translate("Mil's development")?>">
                <?=$this->translate("Mil's development")?>
            </a>
        </div>
    </footer>

    <script type="text/javascript">
        <?=$this->hc_backend_dojojsconfig()?>
    </script>

    <script type="text/javascript">
        <?=$this->hc_backend_huskyjsconfig()?>
    </script>

    <script type="text/javascript" src="/vendor/dojo/dojo.js"></script>
    <script type="text/javascript">
        require({
            paths: {
                "underscore": "/vendor/underscore",
                "underscore.string": "/vendor/underscore.string/lib"
            }
        });
    </script>

    <script>
        require(["dojo/ready",
                 "dojo/dom-style",
                 "dojo/parser",
                 "hc-backend/bootstrap"], function(ready, domStyle) {
                 ready(function(){
                     domStyle.set(dojo.body(), 'visibility', 'visible');
                 });
        });
    </script>
</body>
</html>
